# Generated by Django 5.0.7 on 2024-08-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_subject', models.CharField(max_length=100)),
                ('em_message', models.TextField()),
                ('em_file', models.FileField(upload_to='')),
            ],
        ),
    ]
