# Generated by Django 5.0.7 on 2024-08-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmetafield',
            name='restricted_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
